name: CRD-Lite
on:
  workflow_dispatch:
    inputs:
      crd_code:
        description: 'Code'
        required: true
      crd_pin:
        description: 'PIN'
        required: true
        default: '123456'

jobs:
  start:
    runs-on: windows-latest
    steps:
    - shell: pwsh
      run: |
        # Установка
        $msi = "crd.msi"
        (New-Object Net.WebClient).DownloadFile("https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi", $msi)
        Start-Process msiexec.exe -ArgumentList "/i $msi /qn" -Wait

        # Запуск одной командой (без переменных-массивов)
        & "${Env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="${{ github.event.inputs.crd_code }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=${{ github.event.inputs.crd_pin }}

        # Ожидание (6 часов)
        Write-Host "Ready to connect!"
        while($true) { Start-Sleep -Seconds 3600 }
